springdoc:
  swagger-ui:
    enabled: true
    path: /   # Redirect localhost:8080 to swagger-ui.html

server:
  port: 8080

spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ahriandcat@gmail.com
    password: fjgnzyldxqrskugx
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    protocol: smtp
    test-connection: false